- name: Login + install VC3 latest version of REANA
  hosts: all
  remote_user: "{{ setup_user_name }}"
  become: yes
  become_user: root

  tasks:
    - set_fact:
        #builder_headnode_options: "{{ builder_headnode_options | default('--require noop') }} --require python --require python-pip"
        builder_headnode_options: "{{ builder_headnode_options | default('--require noop') }}"

    - import_tasks: components/common.yaml
    - import_tasks: components/kubernetes.yaml

    - name: Install IUS repo
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: present

    - name: Install python2.7
      yum:
        name: python
        state: present

    - name: Install virtualenv
      yum:
        name: python-virtualenv
        state: present

    - name: Upgrade virtualenv pip
      pip:
        virtualenv: "/usr/local/reana"
        name: pip
        extra_args: --upgrade

    - name: Upgrade virtualenv setuptools
      pip:
        virtualenv: "/usr/local/reana"
        name: setuptools
        extra_args: --upgrade

    - name: Add host IP into /etc/hosts
      command: echo $(curl https://api.ipify.org) $(hostname) >> /etc/hosts

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add docker yum repository
      yum_repository:
        name: docker-ce
        description: Docker CE repo - $basearch
        file: docker-ce
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        sslverify: yes
        gpgcheck: no
      become: yes
    
    - name: Install Docker CE
      yum:
        name: docker-ce-18.06.1.ce
        allow_downgrade: yes

    - name: Install git
      yum:
        name: git
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install kubectl
      shell: |
        curl -Lo /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        # curl -Lo /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl
        chmod +x /usr/bin/kubectl

    - name: Install minikube
      shell: |
        curl -Lo /usr/bin/minikube https://storage.googleapis.com/minikube/releases/v1.0.0/minikube-linux-amd64
        chmod +x /usr/bin/minikube

    - name: Deploy minikube
      shell: |
        mkdir /var/kubernetes
        env MINIKUBE_HOME=/var/kubernetes/.minikube KUBECONFIG=/var/kubernetes/.kube/config minikube start --vm-driver none
        chgrp -R kubernetes /var/kubernetes
        find /var/kubernetes -type d -exec chmod g+rx {} \;
        find /var/kubernetes -type f -exec chmod g+r {} \;

    - name: Setup minikube environment
      shell: |
        echo export MINIKUBE_HOME=/var/kubernetes/.minikube >> /etc/profile.d/kubernetes.sh
        echo export KUBECONFIG=/var/kubernetes/.kube/config >> /etc/profile.d/kubernetes.sh

#    - name: Remove python-ipaddress
#      pip:
#        name: python-ipaddress
#        state: abscent

#    - name: Remove PyYAML
#      pip:
#        name: PyYAML
#        state: abscent

#    - name: Install reana-cluster
#      command: /opt/vc3/home/.local/bin/pip2 install git+https://github.com/khurtado/reana-cluster@job_manager

    - name: Install reana-cluster
      pip:
        name: git+https://github.com/khurtado/reana-cluster@job_manager
        virtualenv: "/usr/local/reana"
        virtualenv_command: virtualenv-2.7

    - name: Install reana-client
      pip:
        name: git+https://github.com/khurtado/reana-client@job_manager
        virtualenv: "/usr/local/reana"
        virtualenv_command: virtualenv-2.7

    - name: Get VC3 reana cluster configuration
      get_url:
        url: https://raw.githubusercontent.com/khurtado/reana-cluster/job_manager/reana_cluster/configurations/reana-cluster-vc3.yaml
        dest: /usr/local/reana/reana-cluster-vc3.yaml
        mode: 0644

    - name: start reana-cluster
      shell: |
        source /usr/local/reana/bin/activate
        reana-cluster -f /usr/local/reana/reana-cluster-vc3.yaml init

    - name: Setup reana-cluster environment
      shell: |
        source /usr/local/reana/bin/activate
        wait_reana(){
          local max_retries=10
          count=0
          until [ $count -ge $max_retries ]
          do
              if reana-cluster status > /dev/null 2>&1; then
                  break
              fi
              ((count++))
              sleep 30
          done
          if [ $count -ge $max_retries ]; then
              echo "Reana did not succeed"
              return 1
          else
              reana-cluster env --include-admin-token > /etc/profile.d/reana.sh
              return 0
          fi
        }
        wait_reana
