---
- import_playbook: components/cvmfs.yaml

- hosts: all
  remote_user: "{{ setup_user_name }}"
  become: yes
  become_user: root

  vars:
    builder_headnode_options: '--require spark-xrootd'

  tasks:
    - import_tasks: components/host.yaml
    - import_tasks: components/users.yaml
    - import_tasks: components/builder.yaml

    - name: create spark config
      copy:
          dest: "/etc/vc3-spark.conf"
          content: |
              spark.driver.port=9000
              spark.blockManager.port=9020
              spark.files.useFetchCache=false
              spark.ui.reverseProxy=true
              spark.authenticate=true
              spark.authenticate.secret={{ lookup('password', '/dev/null length=64') }}

    - name: make secret readable at headnode
      file:
          path: /etc/vc3-spark.conf
          owner: root
          group: wheel
          mode: 0644

    - name: fetch spark config
      fetch:
        src:  /etc/vc3-spark.conf
        dest: "{{ shared_secret_file }}"
        flat: yes


    - name: create spark submit script
      copy:
          dest: /bin/vc3-spark-submit
          content: |
              #! /bin/sh
              spark-submit --properties-file /etc/vc3-spark.conf --master "spark://{{ headnode_ip }}:7077" "$@"

    - name: make submit script executable at headnode
      file:
          path: /bin/vc3-spark-submit
          owner: root
          group: wheel
          mode: 0755

    - name: Start spark
      shell: nohup /bin/vc3-builder --var TERM=linux --var "SPARK_MASTER_HOST={{ headnode_ip }}" --install /opt/vc3/root --distfiles /opt/vc3/distfiles --home /opt/vc3/home --require spark --require python:2.7.14 -- '$VC3_ROOT_SPARK/sbin/start-master.sh --properties-file /etc/vc3-spark.conf' &

